config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/welcome/(:id)' => 'welcome#show', as: :welcome
  get '/client' => 'client#default', as: :client
  get '/client/(:job)' => 'client#output', as: :skills 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  def default
    @clientmessage = "Welcome, potential future employer."
    @clientsubtitle = "Please hire me!"
  end

  def output
    @clientmessage = "Welcome, potential future employer."
    if params[:job]
      @job = params[:job]
    else
       "everything"
    end
  end

  def method_3
    if something
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @welcome = "Welcome to Brents winning page 2."
    @welcome_subtitle = "testing my bootstrap subtitle."
  end

  def show
    if params[:id]
      @id = params[:id].capitalize
    else
      'visitor'.capitalize
    end
  end

  def show_special

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/client/default.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5">
      <h1><%= @clientmessage %></h1>
      <h2><%= @clientsubtitle %></h2>
      <%= image_tag ("amy_s") %>
    </div>
  </div>
</div>
 <%= link_to "Home", root_path %>
 <%= link_to "Skills", skills_path %>

app/views/client/output.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-2">
    <h1><%= @clientmessage %></h1>
    <%= image_tag ("doctor") %>
    <h2> I know a lot about, <%= @job %></h2>
   <%= link_to "Home", root_path %>
   <%=link_to "Back", client_path %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Bootstrappingrails</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-xs-4">

      <h1><%= @welcome %></h1>
      <%= image_tag ("gatsby") %>
      <%= @welcome_subtitle%>
    </div>
  </div>
</div>

<%=link_to "Interested?", client_path %>

app/views/welcome/show.html.erb
<div>
  <h1><%= @id%>, wow, are we glad to have you see the web page!</h1>
</div>